In [1]:
import torch

In [12]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [13]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad  # The gradient is None by default

In [14]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [15]:
y.backward() # y=2x^2
x.grad # dy/dx=4x

tensor([ 0.,  4.,  8., 12.])

In [16]:
x.grad == 4 * x

tensor([True, True, True, True])

In [17]:
x.grad.zero_()  # Reset the gradient
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [21]:
x.grad.zero_()
y=x*x
y.backward(gradient=torch.ones(len(y))) # Faster: y.sum().backward() 
x, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), tensor([0., 2., 4., 6.]))

In [26]:
x.grad.zero_()
y=x*x
u = y.detach()
z=u*x
z.sum().backward()
x.grad == u, u

(tensor([True, True, True, True]), tensor([0., 1., 4., 9.]))

In [27]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [31]:
def f(a):
    b=a*2
    while b.norm() < 1000:
        b=b*2
    if b.sum() > 0:
        c=b
    else:
        c = 100 * b
    return c

In [32]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [33]:
a.grad == d / a

tensor(True)