In [5]:
import torch

In [8]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

In [11]:
x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [12]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [13]:
x[2]

tensor(2)

In [14]:
len(x)

3

In [15]:
x.shape

torch.Size([3])

In [16]:
A = torch.arange(6).reshape(3, 2)
A


tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [17]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [18]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [19]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [20]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [21]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [23]:
a=2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [24]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [25]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [27]:
A.shape, A.sum(axis=0).shape, A.sum(axis=0)

(torch.Size([2, 3]), torch.Size([3]), tensor([3., 5., 7.]))

In [28]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [29]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

In [30]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [31]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [32]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [35]:
A, A / sum_A

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0.0000, 0.3333, 0.6667],
         [0.2500, 0.3333, 0.4167]]))

In [34]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [36]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [37]:
torch.sum(x * y)

tensor(3.)

In [39]:
A.shape, x.shape, A, x, torch.mv(A, x), A@x

(torch.Size([2, 3]),
 torch.Size([3]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]),
 tensor([ 5., 14.]),
 tensor([ 5., 14.]))

In [44]:
B = torch.ones(3, 4)
B, torch.mm(A, B), A@B, A.shape, B.shape, (A@B).shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 torch.Size([2, 3]),
 torch.Size([3, 4]),
 torch.Size([2, 4]))

In [50]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) # L2 norm (Euclidean distance)

tensor(5.)

In [51]:
torch.abs(u).sum() # L1 norm (Manhattan distance, less sensitive to outlier)

tensor(7.)

In [53]:
torch.norm(torch.ones((4, 9))) # Frobenius norm

tensor(6.)

In [52]:
torch.norm(torch.ones((4, 9)))

tensor(6.)